// This file is autogenerated by VESC Tool

#ifndef TMSD_CONFPARSER_H_
#define TMSD_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		1954583966
#define SERIALIZED_CONFIG_LENGTH	248

// Functions
int32_t tmsd_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool tmsd_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void tmsd_confparser_set_defaults_main_config_t(main_config_t *conf);

// TMSD_CONFPARSER_H_
#endif
