// This file is autogenerated by VESC Tool

#ifndef TMSD_CONFXML_H_
#define TMSD_CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_MAIN_CONFIG_T__SIZE		3353

// Variables
extern uint8_t data_main_config_t_[];

// TMSD_CONFXML_H_
#endif
